version: '3.3'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: uvicorn tutorial.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./app/mediafiles:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    env_file:
      - ./.env.prod.db

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - static_volume:/home/app/web/staticfiles
      - ./app/mediafiles:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  data01:
