# Generated by Django 4.1 on 2023-03-12 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0010_post_edited_data_post_tags_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateField(auto_now=True)),
                ('image_field', models.TextField(blank=True, max_length=500)),
                ('file_name', models.TextField(blank=True, max_length=500)),
                ('collections', models.ManyToManyField(blank=True, related_name='collections_history', to='writers.collectionshistory')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_post', to='posts.post')),
                ('writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
