# Generated by Django 4.0 on 2022-01-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts_collections', '0001_initial'),
        ('approve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('post_url', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(blank=True, max_length=250)),
                ('likes', models.IntegerField(blank=True)),
                ('comments', models.IntegerField(blank=True)),
                ('image_field', models.TextField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=5000)),
                ('mentions', models.CharField(blank=True, max_length=5000)),
                ('text_comments', models.CharField(blank=True, max_length=5000)),
                ('alt_name', models.TextField(blank=True, max_length=150)),
                ('file_name', models.TextField(blank=True)),
                ('changed', models.BooleanField(blank=True, default=False)),
                ('edited', models.BooleanField(blank=True, default=False)),
                ('accessed', models.BooleanField(blank=True, default=True)),
                ('unique_field', models.CharField(default='<django.db.models.fields.CharField>_<django.db.models.fields.DateTimeField>', max_length=500, unique=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='posts', to='posts_collections.Collection')),
                ('folder_buy_author', models.ManyToManyField(related_name='posts_in_folder', to='approve.Non_approved')),
                ('hashtags', models.ManyToManyField(blank=True, to='posts.Hashtag')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag_posts', to='posts.Tag')),
            ],
        ),
    ]
