# Generated by Django 4.0 on 2022-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_date_remove_post_hashtags_post_hashtags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
