# Generated by Django 4.0 on 2022-01-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='mentions',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_comments',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
