# Generated by Django 4.1 on 2023-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_data',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_list',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
