# Generated by Django 4.1 on 2023-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_website_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_caption',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]