# Generated by Django 4.0 on 2022-02-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_collections', '0002_collection_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
