# Generated by Django 4.0 on 2022-02-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_collections', '0003_alter_collection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
